### ISSUE TITLE
Female Questions need a skip option

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/reproschema#25]
Expected Behavior: If a male is taking the assessment the option is given to skip a female question
Actual Behavior: A male has to answer questions not applicable

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/162fde4a-24e0-4356-9478-8d01091c0eb1)

**Comment by hotavocado** [comment]
I haven't added conditional logic for this yet. The visibility of this question depends on a question from another activity (pre-questionnaire),  but this functionality hasn't been implemented yet.  For now I'll just manually add a skip button for this one.

**Comment by hotavocado** [comment]
~Need help: @binarybottle @WorldImpex~

Nevermind I figured it out: https://github.com/ReproNim/reproschema/blob/master/activities/EmaHBNEvening/items/good_bad_day#L15

1. Is there currently a way to make an item 'skippable'? What key/value do I need to put in an [item schema](https://github.com/hotavocado/HBN_EMA_NIMH2/blob/master/activities/evening_set/items/Daily9) in order to make an item [skippable](https://github.com/ChildMindInstitute/mindlogger-app/blob/master/app/models/json-ld.js#L152-L261)?

2. If there isn't a key already in use, can we create one?

3. Is someone able to find an example of an item from any protocol that is skippable?

**Comment by WorldImpex** [comment]
Skip still not available 

![File.jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/dadd47d0-f87a-4bb5-8ae5-90a3e2c12904)

**Comment by WorldImpex** [comment]
![File (2).jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/485653e0-6963-474c-a99e-889eced11330)

Fixed
